print("        ___")
print("       /   \\______")
print("      /___        \\____")
print("     /    \____        \\_____")
print("     \\___      \_____        \\____")
print("         \\______     \_____       \\__")
print("                \\____      \____     \\")
print("                     \\___       \__  /")
print("    00000000             \\____     \/")
print("  00       000   00           \\____/")
print(" 00           000 00")
print(" 0                 00")
print("00      mmmm        0")
print("0      mmmmmmm      0")
print("0      mmmmmmm      0")
print("00      mmmmm     000")
print(" 00               0")
print("  000            00")
print("    000       000")
print("       0000000")
